### ISSUE TITLE
TODO release 1.40

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#3045]
Before releasing 1.40 with no mongodb:
- [x] Close [Resulted tmgr.0000.json doesn't contain info about tasks#653](https://github.com/radical-cybertools/radical.entk/issues/653) (Mikhail)
  -  https://github.com/radical-cybertools/radical.entk/pull/654
- [x] Push clean tutorials for them to be compiled by readthedocs (Matteo)
- [ ] Push RP/EnTK README (Matteo)
- [ ] Push EnTK documentation (Matteo)
- [x] Check the requirement file for each package (Mikhail/Andre)
  - RU: https://github.com/radical-cybertools/radical.utils/pull/389
  - RP: https://github.com/radical-cybertools/radical.pilot/pull/3050
  - EnTK: https://github.com/radical-cybertools/radical.entk/pull/655
- [x] Update requirement file for conda (Mikhail/Andre)
- [x] Remove spurious mongodb-related methods from `radical.utils` (Andre)
- [ ] Get all the current users to test devel before release: 
  - [x] FACTS - Alex (Matteo)
  - [x] Cylon - Arup (Aymen)
  - [x] ExaAM - Robert (Mikhail)
    - [x] Summit: no correct executables, but workflow runs
    - [x] Frontier: successful run of the AdditiveFOAM/OpenFOAM workflow
  - [x] RECUP - Özgur/Tianle experiments
  - [x] REPEX - Mason (Matteo)
  - [x] SOMA - Dewi (Matteo)
  - [ ] DeepDriveMD - Hub (Matteo)
  - [x] IMPECCABLE2 - Agastya (Mikhail)
    - ~Issue with Frontier: FS behaves abnormally (also had error `Bus error` before that, not sure if it is connected to FS)~ - **resolved** with re-created VE (Frontier was updated on 10/04)
  - [x] IMPRESS - Jonathan (Matteo)
  - [x] EnTK base example on Lassen (Mikhail)
